version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    volumes:
      - mysql_data:/var/lib/mysql

  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    image: node:10
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysql_data:
